---
swagger: "2.0"
info:
  version: "1.0"
  title: "LatteArt Capture CL"
basePath: "/api/v1"
paths:
  /devices:
    get:
      summary: Get connected device informations.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/DeviceInfo"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ServerError"

definitions:
  ServerError:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            target:
              type: string
  DeviceInfo:
    type: object
    properties:
      platform:
        type: string
        description: "'Android' or 'iOS'"
      id:
        type: string
      name:
        type: string
      osVersion:
        type: string

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
