name: CI

on: [push]

jobs:
  ut:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.3]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn install
          yarn test
